class ZF_AnimatorSetupResult {
	Object localStorage;
	Array<ZF_Element> elements;

	static ZF_AnimatorSetupResult create(Object localStorage) {
		let ret = new("ZF_AnimatorSetupResult");
		ret.localStorage = localStorage;
		return ret;
	}
}

class ZF_Animator abstract ui {
	abstract ZF_AnimatorSetupResult setupOnElement(ZF_ElementContainer elem);
	virtual void tick() {}

	abstract void boxChange(ZF_ElementContainer elem, ZF_AABB old, ZF_AABB new, Object storage);
}
