[archive]
nice_name = "ZForms"
base_file = "zforms/include"

[[archive.markdown_file]]
filename = "test.md"
title = "test"

[[dependency]]
git = "https://github.com/Gutawer/gzdoom"
refname = "origin/documented"
base = "wadsrc/static"
url = "http://localhost:8081"
