[archive]
nice_name = "ZForms"
base_file = "zforms/include"

[[archive.markdown_file]]
filename = "test.md"
title = "test"

[[dependency]]
git = "https://gitlab.com/Gutawer/gzdoom_pk3_doc.git"
refname = "origin/main"
base = "wadsrc/static"
url = "http://localhost:8081"
